# Generated by Django 5.0.3 on 2024-04-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=40)),
                ('modelo', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=20)),
                ('año', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
