# Generated by Django 4.2.11 on 2024-04-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCandas', '0002_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=40)),
                ('marca', models.CharField(max_length=40)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
